import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import Modal from './Component/Modal/Modal';


export default function Home() {
  const [users, setUsers] = useState([])
  const [formulario, setFormulario] = useState("");
  const [idUser, setIdUser] = useState(0);
  
  // Modal
  const [dropdown, setDropdown] = useState(false);
  const [textoModal, setTextoModal] = useState(false);
  
  const getAll = () => {
    fetch('/api/users')
    .then((res) => res.json())
    .then((data) => {
      setUsers(data)
    })
  }

  useEffect(() => {

    getAll();
    
  }, [])

  
  const adicionar = () => {
    setFormulario("create");
    setTextoModal("Novo Usuário");
    setDropdown(true);
  }


  const editar = (id) => {

    setIdUser(id)
    setFormulario("update");
    setTextoModal("Editar Usuário");

    setDropdown(true);
  }

  const openClose = () => {
    setDropdown(!dropdown);
  }

  const formSubmit = (event) => {
    console.log('formSubmit')
    event.preventDefault();
    // iniciar requisição 
    let users = {
      "nome": event.target[0].value,
      "email": event.target[1].value,
      "idade": event.target[2].value
    }

    submit(users);
  }

  const submit = (users) => {
    switch (formulario) {
      case "create":
        create(users);
        break;
      case "update":
        update(idUser, users);
        break;
      case "delete":
        deletepedido(idUser);
        break;
        
      default:
        break;
    }
  }

  const create = (users) => {
    const requestOptions = {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(users)
    };
    fetch('/api/users', requestOptions)
      .then(response => response.json())
      .then(data => console.log("update - users") )
      .finally(() => {
        // reseta tudo
        setIdUser(0);
        getAll();
        openClose();
      });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button variant="primary" onClick={(e) =>adicionar()} size="lg">Novo usuário</button>
        <table className="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Nome</th>
              <th scope="col">Email</th>
              <th scope="col">Idade</th>

              <th scope="col">editar / deletar</th>
            </tr>
          </thead>
          <tbody>
            {users.map(user=>(
              <tr>
                <th scope="row">{user.ID}</th>
                <td>{user.NOME}</td>
                <td>{user.EMAIL}</td>
                <td>{user.IDADE}</td>
                <td>
                    <button variant="primary" onClick={(e) =>editar(user.ID)} size="lg">Editar</button>
                    {' '}
                    <button variant="danger" onClick={(e) =>deletar(user.ID)} size="lg">Deletar</button>
                    {' '}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
          
        <Modal hidden={dropdown} openClose={openClose} textoModal={textoModal} formSubmit={formSubmit}/>
      </main>
    </>
  )
}
